"""Wires the tracker into Claude Code's ``settings.json``.

Adds a statusline badge and SessionStart/Stop reminder hooks, merging into any
existing settings (it preserves other plugins, e.g. a custom statusline) and
always backing the file up first. Fully reversible with :func:`uninstall`.
"""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

from .config import CLAUDE_DIR

SETTINGS_PATH = CLAUDE_DIR / "settings.json"
STATUSLINE_SCRIPT = CLAUDE_DIR / "token-tracker" / "statusline.sh"

# Marker so uninstall can find exactly the hooks we added.
HOOK_MARKER = "claude_fair_share.cli"
_CHECK_CMD = f"{sys.executable} -m {HOOK_MARKER.rsplit('.', 1)[0]} check"


def _statusline_command() -> str:
    return f'bash "{STATUSLINE_SCRIPT}"'


def _load_settings() -> dict:
    if not SETTINGS_PATH.exists():
        return {}
    try:
        return json.loads(SETTINGS_PATH.read_text())
    except json.JSONDecodeError:
        raise SystemExit(f"refusing to edit unparseable {SETTINGS_PATH}")


def _backup() -> Path | None:
    if not SETTINGS_PATH.exists():
        return None
    backup = SETTINGS_PATH.with_suffix(".json.bak")
    shutil.copy2(SETTINGS_PATH, backup)
    return backup


def _our_hook_entry() -> dict:
    return {"hooks": [{"type": "command", "command": _CHECK_CMD}]}


def _add_hook(settings: dict, event: str) -> None:
    hooks = settings.setdefault("hooks", {})
    entries = hooks.setdefault(event, [])
    for entry in entries:
        for hook in entry.get("hooks", []):
            if hook.get("command") == _CHECK_CMD:
                return  # already installed
    entries.append(_our_hook_entry())


def _remove_hook(settings: dict, event: str) -> None:
    hooks = settings.get("hooks", {})
    entries = hooks.get(event)
    if not entries:
        return
    kept = [
        entry
        for entry in entries
        if not any(h.get("command") == _CHECK_CMD for h in entry.get("hooks", []))
    ]
    if kept:
        hooks[event] = kept
    else:
        hooks.pop(event, None)
    if not hooks:
        settings.pop("hooks", None)


def install(write_statusline: bool = True) -> list[str]:
    """Install statusline + hooks. Returns a list of human-readable actions."""
    actions: list[str] = []
    settings = _load_settings()
    backup = _backup()
    if backup:
        actions.append(f"backed up settings -> {backup}")

    if write_statusline:
        existing = settings.get("statusLine", {}).get("command", "")
        if STATUSLINE_SCRIPT.name not in existing:
            STATUSLINE_SCRIPT.parent.mkdir(parents=True, exist_ok=True)
            STATUSLINE_SCRIPT.write_text(_render_statusline_script(existing))
            STATUSLINE_SCRIPT.chmod(0o755)
            settings["statusLine"] = {
                "type": "command",
                "command": _statusline_command(),
            }
            actions.append("installed statusline badge (chained after any existing one)")

    _add_hook(settings, "SessionStart")
    _add_hook(settings, "Stop")
    actions.append("added SessionStart + Stop threshold-reminder hooks")

    SETTINGS_PATH.parent.mkdir(parents=True, exist_ok=True)
    SETTINGS_PATH.write_text(json.dumps(settings, indent=2))
    return actions


def uninstall() -> list[str]:
    """Remove our hooks; leave statusline pointed at the wrapper (which is safe
    on its own). Returns a list of actions."""
    actions: list[str] = []
    if not SETTINGS_PATH.exists():
        return ["nothing to do (no settings.json)"]
    settings = _load_settings()
    _backup()
    _remove_hook(settings, "SessionStart")
    _remove_hook(settings, "Stop")
    actions.append("removed SessionStart + Stop hooks")
    SETTINGS_PATH.write_text(json.dumps(settings, indent=2))
    actions.append(
        "left statusLine in place; to drop the badge too, restore the .bak file"
    )
    return actions


def _render_statusline_script(prior_command: str) -> str:
    """A wrapper that runs any prior statusline command, then appends our badge.

    ``prior_command`` is whatever ``statusLine.command`` was before install, so
    an existing statusline (e.g. a plugin's) keeps rendering.
    """
    chain = ""
    if prior_command and STATUSLINE_SCRIPT.name not in prior_command:
        chain = (
            "# run the statusline that was configured before install, then "
            "append our badge\n"
            f'printf "%s" "$input" | {prior_command}\n'
            'printf " "\n'
        )
    return (
        "#!/bin/bash\n"
        "# Auto-generated by claude-token-tracker. Renders the local token "
        "badge,\n# chained after any previously configured statusline.\n"
        "input=$(cat)\n"
        f"{chain}"
        f'{sys.executable} -m {HOOK_MARKER.rsplit(".", 1)[0]} statusline 2>/dev/null\n'
    )
